### ISSUE TITLE
100节点大规模集群时，kube-state-metric报内存溢出

### ISSUE THREAD

**Issue by tmon546596046** [vmeta42/metashow#15]
managed cluster：
```
  - containerID: docker://f8746a7ba8d20edbedcb20f3c3c2aecf89980a744453e0d2222659daa292d98d
    image: core.harbor.domain/library/kube-state-metrics:v2.0.0
    imageID: docker-pullable://core.harbor.domain/library/kube-state-metrics@sha256:ee13833414a49b0d2370e8edff5844eba96630cda80cfcd37c444bf88522cc51
    lastState:
      terminated:
        containerID: docker://f8746a7ba8d20edbedcb20f3c3c2aecf89980a744453e0d2222659daa292d98d
        exitCode: 137
        finishedAt: "2022-11-09T01:45:57Z"
        reason: OOMKilled
        startedAt: "2022-11-09T01:45:45Z"
    name: kube-state-metrics
    ready: false
    restartCount: 74
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=kube-state-metrics pod=kube-state-metrics-84fb48777f-5qsqp_monitoring(7ab38671-6ea7-4a4b-b9ad-5b91deacb820)
        reason: CrashLoopBackOff
  hostIP: 10.120.0.45
  phase: Running
  podIP: 10.253.17.51
  podIPs:
  - ip: 10.253.17.51
  qosClass: Burstable
  startTime: "2022-09-26T10:19:09Z"
```
